# Generated by Django 2.2.5 on 2020-09-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191204_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Важность',
                'verbose_name_plural': 'Важность',
            },
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='tasks.Priority'),
        ),
        migrations.CreateModel(
            name='HIGH',
            fields=[
                ('priority_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Priority')),
                ('pr', models.CharField(default='PRIORITY_HIGH', max_length=15, verbose_name='PRIORITY_HIGH')),
            ],
            bases=('tasks.priority',),
        ),
        migrations.CreateModel(
            name='LOW',
            fields=[
                ('priority_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Priority')),
                ('pr', models.CharField(default='PRIORITY_LOW', max_length=15, verbose_name='PRIORITY_LOW')),
            ],
            bases=('tasks.priority',),
        ),
        migrations.CreateModel(
            name='MEDIUM',
            fields=[
                ('priority_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Priority')),
                ('pr', models.CharField(default='PRIORITY_MEDIUM', max_length=15, verbose_name='PRIORITY_MEDIUM')),
            ],
            bases=('tasks.priority',),
        ),
    ]
