# Generated by Django 2.2.5 on 2020-09-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200923_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='low',
            name='priority_ptr',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='priority_ptr',
        ),
        migrations.AddField(
            model_name='priority',
            name='prior',
            field=models.IntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=2, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_priority', to='tasks.Priority'),
        ),
        migrations.DeleteModel(
            name='HIGH',
        ),
        migrations.DeleteModel(
            name='LOW',
        ),
        migrations.DeleteModel(
            name='MEDIUM',
        ),
    ]
