# Generated by Django 2.2.5 on 2020-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200923_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='prior',
            field=models.IntegerField(default=2, verbose_name='Важность'),
        ),
    ]
